version: "3.9"
services:
    mainpage-node:
        build:
            context: docker/development/node
        environment:
            WDS_SOCKET_PORT: 0
            NODE_ENV: development
            REACT_APP_API_URL: http://api.localhost/api/v1/
        volumes:
            - ./:/app:rw
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn start"
        tty: true
        networks:
            - traefik-public

    mainpage-node-cli:
        build:
            context: docker/development/node
        volumes:
            - ./:/app
        networks:
            - traefik-public

    mainpage:
        build:
            context: docker/development/nginx
        networks:
            - traefik-public
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.mainpage.entrypoints=http
            - traefik.http.routers.mainpage.rule=Host(`frontend.localhost`) || Host(`front.localhost`)
            - traefik.http.services.mainpage.loadBalancer.server.port=80

networks:
    traefik-public:
        external: true